### ISSUE TITLE
package.json is missing webpack-stream

### ISSUE THREAD

**Issue by bryonchan** [sympmarc/SPServices#35]
Hi all,
Just tried to build using gulp and got this error. Will submit a pull request to fix this, if all right with you guys?

`Error: Cannot find module 'webpack-stream'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\Users\bchan\Work\SPServices\Gulpfile.js:12:15)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)`

**Comment by purtuga** [comment]
Just submitted a fix for this - pull #39

**Comment by sympmarc** [comment]
Should be fixed in pull #39.
